CREATE DATABASE progetto_finale;

USE progetto_finale;

CREATE TABLE IF NOT EXISTS utente (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) DEFAULT '',
    cognome VARCHAR(255) DEFAULT '',
	email VARCHAR(255) DEFAULT '',
	password  VARCHAR(255) DEFAULT NULL
        
); 

CREATE TABLE IF NOT EXISTS tempo (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    nome_citta VARCHAR(255) DEFAULT '',
    temperatura DECIMAL(10,2) DEFAULT 0,
	max_temp DECIMAL(10,2) DEFAULT 0,
    min_temp DECIMAL(10,2) DEFAULT 0,
    umidita INT DEFAULT 0,
	tempo  VARCHAR(255) DEFAULT ''
);

CREATE TABLE utente_tempo (
  fk_u int NOT NULL,
  fk_t int NOT NULL,
  PRIMARY KEY (fk_u, fk_t),
  FOREIGN KEY (fk_u) REFERENCES utente (ID) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (fk_t) REFERENCES tempo (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

